stages:
  preprocess:
    cmd: python -m eeg_win_stack.pipeline.preprocess
    params:
      - eeg_win_stack/config/params.toml:
          - data
          - preprocessing
          - windowing
          - run
    outs:
      - target/saved_windows:
          cache: true

  train:
    cmd: python -m eeg_win_stack.pipeline.train
    deps:
      - ./target/saved_windows
    params:
      - eeg_win_stack/config/params.toml:
          - split
          - training
          - model
          - run
    outs:
      - target/saved_models:
          cache: true

  evaluate:
    cmd: python -m eeg_win_stack.pipeline.evaluate
    deps:
      - .\target\saved_windows
      - .\target\saved_models
    params:
      - eeg_win_stack/config/params.toml:
          - split
          - model
          - run
    metrics:
      - metrics.json:
          cache: false
  
  decision:
    cmd: python -m eeg_win_stack.pipeline.decision
    params:
      - eeg_win_stack/config/params.toml:
          - decision
          - run
    outs:
      - target/decision_results.csv:
          cache: false
    metrics:
      - decision_metrics.json:
          cache: false
